spring.application.name=openstudy

spring.datasource.url=jdbc:mysql://localhost:3306/openstudy_db
spring.datasource.username=root
spring.datasource.password=[YOUR PASSWORD HERE]
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.sql.init.mode=never